django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/common/', include('common.urls')),
    path('api/board/', include('board.urls')),
    path('api/statistic/', include('statistic.urls')),
    path('api/log/', include('log.urls')),
]

django/log/urls.py
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views


urlpatterns = format_suffix_patterns([
    path('', views.api_root),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('logs/', views.LogsView.as_view(), name='logs'),
])

django/user/urls.py
from django.urls import path

from . import views

app_name = 'user' # name space지정해주면 하드코딩으로부터 벗어날 수 있다. 
urlpatterns = [
    path('', views.index, name='index'), # 기존 ayaan에서 user로 매핑되었기때문에 홈디렉토리가됨
    path('<int:question_id>/', views.detail, name='detail'), #/ 빼먹지말자
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

django/board/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

User = settings.AUTH_USER_MODEL


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.id)


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.id)

django/user/forms.py
from django import forms
from user.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

django/user/views.py
from django.shortcuts import render, get_object_or_404, redirect

# from django.http import HttpResponse
# Create your views here.
from .models import Question, Answer
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from .forms import QuestionForm, AnswerForm

# from django.http import HttpResponseNotAllowed
from django.core.paginator import Paginator  # 페이징 라이브러리
from django.contrib.auth.decorators import (
    login_required,
)  # @login_required 애너테이션이 붙은 함수는 로그인이 필요한 함수를 의미


def index(request):
    page = request.GET.get("page", "1")  # 페이지
    question_list = Question.objects.order_by("-create_date")
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {"question_list": page_obj}
    return render(request, "user/question_list.html", context)


@csrf_exempt
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "user/question_detail.html", context)


@login_required(login_url="common:login")  # 로그아웃인 상태에서 작성시 로그인화면으로
def answer_create(request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    # return redirect('user:detail', question_id=question.id)
    # -----------------위나 아래와 같은 방식으로도 사용 가능----------------
    # question = get_object_or_404(Question, pk=question_id)
    # answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    # answer.save()
    # return redirect('user:detail', question_id=question.id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect("user:detail", question_id=question.id)
    else:
        form = AnswerForm()  # 로그아웃시에 답변을 등록하더라도 오류가 안생기고 상세화면으로 돌아감 아래는 오류발생시키는 코드
        # return HttpResponseNotAllowed('Only POST is possible.')
    context = {"question": question, "form": form}
    return render(request, "user/question_detail.html", context)


@login_required(login_url="common:login")  # 로그아웃인 상태에서 작성시 로그인화면으로
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():  # 폼이 유효하다면
            question = form.save(commit=False)  # 임시 저장하여 question 객체를 리턴받는다.
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()  # 실제 저장을 위해 작성일시를 설정한다.
            question.save()  # 데이터를 실제로 저장한다.
            return redirect("user:index")
    else:
        form = QuestionForm()
    context = {"form": form}
    return render(request, "user/question_form.html", context)

from django.contrib import messages
@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('user:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('user:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'user/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('user:detail', question_id=question.id)
    question.delete()
    return redirect('user:index')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('user:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('user:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'user/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('user:detail', question_id=answer.question.id)

django/templates/user/question_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3">
        <!-- message 표시 -->
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
        </div>
        {% endif %}
        <!-- 질문 -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2">{{ question.author.username }}</div>
                        <div>{{ question.create_date }}</div>   
                    </div>
                    <div class="my-3">
                        {% if request.user == question.author %}
                        <a href="{% url 'user:question_modify' question.id  %}" 
                            class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'user:question_delete' question.id  %}">삭제</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- 답변 -->
        <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
        {% for answer in question.answer_set.all %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                <div class="my-3">
                    {% if request.user == answer.author %}
                    <a href="{% url 'user:answer_modify' answer.id  %}" 
                        class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                        data-uri="{% url 'user:answer_delete' answer.id  %}">삭제</a>
                    {% endif %}
                </div>
                </div>
            </div>
        {% endfor %}
        <!-- 답변 등록 -->
        <form
            action="{% url 'user:answer_create' question.id %}"
            method="post"
            class="my-3">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <div>
                                <strong>{{ field.label }}</strong>
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <h3>
                    <label for="content" class="form-label">답변</label>
                </h3>
                <!--로그인 상태가 아닌 경우 textarea 태그에 disabled 속성을 적용하여 입력을 못함 is_anonymous(로그아웃 여부)와
                is_authenticated(로그인 여부)는 반대개념-->
                <textarea {% if not user.is_authenticated %}disabled{% endif %}
                name="content" id="content" class="form-control" rows="10" placeholder="내용을 입력 하세요"></textarea>
                </div>
            <input type="submit" value="답변등록" class="btn btn-primary" style="float: right;">
        </form>
    </div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

django/templates/user/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
<!--다시 서버구동해야 작동-->
{% block content %}
    <div class="container my-3">
        <table class="table">
            <thead>
                <tr class="text-center table-danger">
                    <th>번호</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                    <th>작성일시</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                    {% for question in question_list %}
                    <tr class="text-center">
                        <td>
                            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td class="text-start">
                            <a href="{% url 'user:detail' question.id %}">{{ question.subject }}</a>
                            {% if question.answer_set.count > 0 %}
                            <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                            {% endif %}
                        </td>
                        <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
                        <td>{{ question.create_date }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="4">질문이 없습니다.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                    {% if page_number == question_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        <a href="{% url 'user:question_create' %}" class="btn btn-primary" style="float: right;">질문 등록하기</a>
    </div>
{% endblock %}